### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Snogard** [zeldamods/oead#21]
```
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc: In function ‘bool absl::SetupAlternateStackOnce()’:
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:139:32: error: no matching function for call to ‘max(long int, int)’
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
      |                        ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/algorithm:60,
                 from /home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:36:
/usr/include/c++/12.1.0/bits/stl_algobase.h:254:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)’
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/12.1.0/bits/stl_algobase.h:254:5: note:   template argument deduction/substitution failed:
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:139:32: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
      |                        ~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/c++/12.1.0/bits/stl_algobase.h:300:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)’
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/include/c++/12.1.0/bits/stl_algobase.h:300:5: note:   template argument deduction/substitution failed:
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:139:32: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long int’ and ‘int’)
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
      |                        ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/algorithm:61:
/usr/include/c++/12.1.0/bits/stl_algo.h:5746:5: note: candidate: ‘template<class _Tp> constexpr _Tp std::max(initializer_list<_Tp>)’
 5746 |     max(initializer_list<_Tp> __l)
      |     ^~~
/usr/include/c++/12.1.0/bits/stl_algo.h:5746:5: note:   template argument deduction/substitution failed:
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:139:32: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long int’
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
      |                        ~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/include/c++/12.1.0/bits/stl_algo.h:5756:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr _Tp std::max(initializer_list<_Tp>, _Compare)’
 5756 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/include/c++/12.1.0/bits/stl_algo.h:5756:5: note:   template argument deduction/substitution failed:
/home/snogard/.cache/paru/clone/python-oead/src/oead/lib/abseil/absl/debugging/failure_signal_handler.cc:139:32: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long int’
  139 |   size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
      |                        ~~~~~~~~^~~~~~~~~~~~~~~~~
make[2]: *** [oead/lib/abseil/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/build.make:76: oead/lib/abseil/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/failure_signal_handler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1378: oead/lib/abseil/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Linking CXX static library libabsl_cordz_handle.a
[ 83%] Built target absl_cordz_handle
[ 83%] Linking CXX static library libabsl_hashtablez_sampler.a
[ 83%] Built target absl_hashtablez_sampler
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/home/snogard/.cache/paru/clone/python-oead/src/oead/setup.py", line 64, in <module>
    setuptools.setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/snogard/.cache/paru/clone/python-oead/src/oead/setup.py", line 29, in run
    self.build_extension(ext)
  File "/home/snogard/.cache/paru/clone/python-oead/src/oead/setup.py", line 55, in build_extension
    subprocess.check_call([cmake_name, '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j4', '--config', 'Release']' returned non-zero exit status 2.
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'python-oead-1.2.3-2': 
error: packages failed to build: python-oead-1.2.3-2

```

**Comment by leoetlino** [comment]
Ah, sorry, I forgot to tag a new release after merging the Abseil update (#20).

1.2.4 will be available on PyPI shortly.

**Comment by leoetlino** [comment]
Looks like something went wrong while uploading the wheels. I'm looking into the issue.

**Comment by leoetlino** [comment]
1.2.4-1 has now been published, so this installation issue should be fixed.

**Comment by Snogard** [comment]
thank you! i was able to build the package
