### ISSUE TITLE
1.2.4-1 does not contain the readme.rst file 

### ISSUE THREAD

**Issue by kutal10** [zeldamods/oead#22]
Looks like the 1.2.4-1 tar.gz file is missing the readme.rst 

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rahul\AppData\Local\Temp\pip-install-9pju7qrd\oead\setup.py", line 58, in <module>
        with open("readme.rst", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'

**Comment by leoetlino** [comment]
Whoops. Looks like I forgot to add it to the MANIFEST.in file...

**Comment by leoetlino** [comment]
Should be fixed in 1.2.4-2. Thanks for reporting!
