### ISSUE TITLE
No available build for ARM64 systems

### ISSUE THREAD

**Issue by SDarkMagic** [zeldamods/oead#8]
I've been trying to install oead on some ARM64 systems lately, and keep running into the issue of there not being a package on pip for that architecture. I've tried building from the source, but haven't had any luck with that either. I was wondering if you would mind creating and uploading a package that functions on ARM64 devices? Thanks!

**Comment by leoetlino** [comment]
I'm afraid I probably can't provide prebuilt packages for ARM64 considering that there is no ARM64 GitHub Actions environment... What goes wrong when you build?

**Comment by SDarkMagic** [comment]
When I try to build it, it throws this error (python setup.py install)
```
/usr/lib/python3/dist-packages/setuptools/dist.py:475: UserWarning: Normalizing 'v1.1.3-1+1.gd08bacb.dirty' to '1.1.3.post1+1.gd08bacb.dirty'
  normalized_version,
running install
running bdist_egg
running egg_info
writing oead.egg-info/PKG-INFO
writing dependency_links to oead.egg-info/dependency_links.txt
writing top-level names to oead.egg-info/top_level.txt
reading manifest file 'oead.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'oead.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_ext
-- pybind11 v2.4.dev4
-- ryml: using C++ standard: C++11
-- ryml: setting global C++ standard: 11
-- ryml: importing subproject c4core (SUBDIRECTORY)... /home/pi/Desktop/oead/lib/rapidyaml/ext/c4core
-- c4core: using C++ standard: C++11
-- c4core: setting global C++ standard: 11
-- ryml: -----> target ryml PUBLIC incorporating lib c4core
-- Using CMake version 3.13.4
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'armv6'
-- Basearch of 'armv6' has been detected as: 'arm'
-- Architecture supports unaligned reads
-- Architecture-specific source files: arch/arm/armfeature.c;arch/arm/fill_window_arm.c;arch/arm/adler32_neon.c;arch/arm/crc32_acle.c;arch/arm/insert_string_acle.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Release (selected)
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_ACLE, Build with ACLE
 * WITH_NEON, Build with NEON intrinsics
 * NEON_FILLWINDOW, Support NEON instructions in fill_window_arm, using "-mfloat-abi=hard -mfpu=neon"
 * ACLE_CRC, Support CRC hash generation using the ACLE instruction set, using "-march=armv8-a+crc"

-- The following REQUIRED packages have been found:

 * PythonInterp
 * PythonLibsNew
 * Threads

-- The following features have been disabled:

 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
 * WITH_CODE_COVERAGE, Enable code coverage reporting

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Desktop/oead/build/temp.linux-armv7l-3.7
[  9%] Built target zlib
[ 14%] Built target oead_res
[ 15%] Built target absl_spinlock_wait
[ 16%] Built target absl_log_severity
[ 17%] Built target absl_raw_logging_internal
[ 18%] Built target absl_throw_delegate
[ 19%] Built target absl_dynamic_annotations
[ 22%] Built target absl_base
[ 23%] Built target absl_malloc_internal
[ 24%] Built target absl_exponential_biased
[ 25%] Built target absl_bad_optional_access
[ 30%] Built target absl_time_zone
[ 32%] Built target absl_debugging_internal
[ 33%] Built target absl_demangle_internal
[ 34%] Built target absl_symbolize
[ 35%] Built target absl_stacktrace
[ 35%] Built target absl_int128
[ 37%] Built target absl_strings_internal
[ 42%] Built target absl_strings
[ 43%] Built target absl_graphcycles_internal
[ 43%] Built target absl_civil_time
[ 45%] Built target absl_time
[ 48%] Built target absl_synchronization
[ 50%] Built target absl_hashtablez_sampler
[ 50%] Built target absl_raw_hash_set
[ 51%] Built target absl_city
[ 52%] Built target absl_cord
[ 52%] Built target absl_bad_variant_access
[ 52%] Built target absl_hash
[ 55%] Built target absl_str_format_internal
[ 59%] Built target yaml
[ 64%] Built target ryml
[ 64%] Building CXX object oead/CMakeFiles/oead.dir/src/gsheet.cpp.o
In file included from /home/pi/Desktop/oead/src/gsheet.cpp:25:
/home/pi/Desktop/oead/src/include/oead/gsheet.h:56:33: error: static assertion failed
 static_assert(sizeof(ResHeader) == 0x30);
               ~~~~~~~~~~~~~~~~~~^~~~~~~
/home/pi/Desktop/oead/src/include/oead/gsheet.h:154:32: error: static assertion failed
 static_assert(sizeof(ResField) == 0x30);
               ~~~~~~~~~~~~~~~~~^~~~~~~
/home/pi/Desktop/oead/src/include/oead/gsheet.h:173:34: warning: ‘maybe_unused’ attribute ignored [-Wattributes]
   [[maybe_unused]] u32 padding = 0;
                                  ^
/home/pi/Desktop/oead/src/include/oead/gsheet.h:185:34: warning: ‘maybe_unused’ attribute ignored [-Wattributes]
   [[maybe_unused]] u32 padding = 0;
                                  ^
/home/pi/Desktop/oead/src/include/oead/gsheet.h:264:28: error: static assertion failed
 static_assert(sizeof(Data) == 0x10);
               ~~~~~~~~~~~~~^~~~~~~
/home/pi/Desktop/oead/src/gsheet.cpp:49:34: warning: ‘maybe_unused’ attribute ignored [-Wattributes]
   [[maybe_unused]] u32 padding = 0;
                                  ^
/home/pi/Desktop/oead/src/gsheet.cpp:51:35: error: static assertion failed
 static_assert(sizeof(OpaqueArray) == 0x10);
               ~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[2]: *** [oead/CMakeFiles/oead.dir/build.make:115: oead/CMakeFiles/oead.dir/src/gsheet.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: oead/CMakeFiles/oead.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 29, in run
    self.build_extension(ext)
  File "setup.py", line 55, in build_extension
    subprocess.check_call([cmake_name, '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 2.
```

**Comment by leoetlino** [comment]
Sounds like it's trying to make a 32-bit build (armv7l), *not* AArch64. Are you sure your system is actually 64-bit?

**Comment by SDarkMagic** [comment]
oops, my bad-it is 32 bit XD

**Comment by leoetlino** [comment]
Well, let me know if you cannot build this on AArch64.
